#!/bin/bash
# gate1-kit/scripts/setup-gpg.sh <sandbox_root>
# Creates the drill key material:
#   <root>/gpg-backup   — PUBLIC key only (stands in for the backup host)
#   <root>/gpg-restore  — keyring holding the PRIVATE key (restore host only)
#
# DRILL USE ONLY. Production uses the hospital key facility (HSM/KMS/vault,
# task B-18) — never a passphrase-less key generated by a script.

set -euo pipefail

ROOT="${1:?usage: setup-gpg.sh <sandbox_root>}"
BACKUP_GNUPGHOME="${ROOT}/gpg-backup"
RESTORE_GNUPGHOME="${ROOT}/gpg-restore"
KEY_UID="AIGH NurseApp Drill Key <drill@sandbox.invalid>"

rm -rf "${BACKUP_GNUPGHOME}" "${RESTORE_GNUPGHOME}"
mkdir -p "${BACKUP_GNUPGHOME}" "${RESTORE_GNUPGHOME}"
chmod 700 "${BACKUP_GNUPGHOME}" "${RESTORE_GNUPGHOME}"

# Generate the keypair in the restore keyring (the only place the private key lives)
gpg --batch --quiet --homedir "${RESTORE_GNUPGHOME}" \
    --pinentry-mode loopback --passphrase '' \
    --quick-generate-key "${KEY_UID}" rsa3072 encrypt never 2>/dev/null

# Export ONLY the public key into the backup keyring
gpg --batch --quiet --homedir "${RESTORE_GNUPGHOME}" --armor --export > "${ROOT}/backup.pub"
gpg --batch --quiet --homedir "${BACKUP_GNUPGHOME}" --import "${ROOT}/backup.pub" 2>/dev/null

echo "GPG setup complete"
echo "  backup host keyring (public only): ${BACKUP_GNUPGHOME}"
echo "  restore host keyring (private)   : ${RESTORE_GNUPGHOME}"
echo "  public key file                  : ${ROOT}/backup.pub"

# Prove the separation: the backup keyring must NOT be able to decrypt.
echo "backup keyring secret keys:  $(gpg --homedir "${BACKUP_GNUPGHOME}" --list-secret-keys 2>/dev/null | grep -c '^sec' || true)"
echo "restore keyring secret keys: $(gpg --homedir "${RESTORE_GNUPGHOME}" --list-secret-keys 2>/dev/null | grep -c '^sec' || true)"
